- name: OBTAIN SESSION COOKIE WITH URI MODULE
  hosts: all
  connection: local
  gather_facts: no
  tasks:
    - name: Get cookie with POST
      uri:
        url: "https://{{ inventory_hostname }}:8443/j_security_check"
        method: POST
        body:
          j_username: "{{ username }}"
          j_password: "{{ password }}"
        body_format: form-urlencoded
        return_content: yes
        validate_certs: no
      register: login_data

    - name: Assign the session cookie to a variable
      set_fact:
        vmanage_cookie: "{{ login_data.set_cookie }}"

    - name: GET Reboot History Details
      uri:
        url: "https://{{ inventory_hostname }}:8443/dataservice/device/reboothistory/details"
        method: GET
        headers:
          Cookie: "{{ vmanage_cookie }}"
        return_content: yes
        validate_certs: no
      register: reboot_history

    - name: Print Reboot History
      debug:
        var: reboot_history
