---
- name: Check policy configurations
  hosts: all
  connection: local
  roles:
    - ansible-viptela
  tasks:
    - name: GET POLICY LISTS
      vmanage_policy_list_facts:
        host: "{{ inventory_hostname }}"
        user: "{{ username }}"
        password: "{{ password }}"
      no_log: yes
      register: lists_facts

    - name: PRINT POLICY LISTS
      debug:
        msg: "{{ lists_facts.policy_lists | selectattr('type', 'match', '(site|vpn)') | list }}"

    - name: GET POLICY DEFINITIONS
      vmanage_policy_definition_facts:
        host: "{{ inventory_hostname }}"
        user: "{{ username }}"
        password: "{{ password }}"
      no_log: yes
      register: definitions_facts

    - name: PRINT POLICY DEFINITIONS
      debug: var=definitions_facts.policy_definitions

    - name: GET CENTRAL POLICIES
      vmanage_central_policy_facts:
        host: "{{ inventory_hostname }}"
        user: "{{ username }}"
        password: "{{ password }}"
      no_log: yes
      register: central_policies_facts

    - name: PRINT CENTRAL POLICIES
      debug: var=central_policies_facts.central_policies
